create table if not exists public.app_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now())
);

alter table public.app_admins enable row level security;

drop policy if exists "app_admins_self_read" on public.app_admins;
create policy "app_admins_self_read"
on public.app_admins
for select
to authenticated
using (user_id = auth.uid());

create table if not exists public.site_updates (
    id bigint generated by default as identity primary key,
    title text,
    body text,
    image_data_url text,
    video_data_url text,
    show_on_startup boolean not null default false,
    is_published boolean not null default true,
    author_id uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.site_updates
add column if not exists video_data_url text;

create index if not exists idx_site_updates_created_at on public.site_updates (created_at desc);
create index if not exists idx_site_updates_startup on public.site_updates (show_on_startup, created_at desc);

create or replace function public.set_site_updates_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_site_updates_updated_at on public.site_updates;
create trigger trg_site_updates_updated_at
before update on public.site_updates
for each row
execute function public.set_site_updates_updated_at();

alter table public.site_updates enable row level security;

drop policy if exists "site_updates_public_read" on public.site_updates;
create policy "site_updates_public_read"
on public.site_updates
for select
using (is_published = true);

drop policy if exists "site_updates_admin_insert" on public.site_updates;
create policy "site_updates_admin_insert"
on public.site_updates
for insert
to authenticated
with check (
    author_id = auth.uid()
    and exists (
        select 1
        from public.app_admins admin
        where admin.user_id = auth.uid()
    )
);

drop policy if exists "site_updates_admin_update" on public.site_updates;
create policy "site_updates_admin_update"
on public.site_updates
for update
to authenticated
using (
    exists (
        select 1
        from public.app_admins admin
        where admin.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.app_admins admin
        where admin.user_id = auth.uid()
    )
);

drop policy if exists "site_updates_admin_delete" on public.site_updates;
create policy "site_updates_admin_delete"
on public.site_updates
for delete
to authenticated
using (
    exists (
        select 1
        from public.app_admins admin
        where admin.user_id = auth.uid()
    )
);

-- Rode esta linha depois, trocando pelo seu e-mail real do Supabase Auth.
-- insert into public.app_admins (user_id)
-- select id from auth.users where email = 'SEU_EMAIL_AQUI';
